name: Prod build and deployment
on:
  push:
    branches:
      - 'main'
jobs:
  BuildSimulation:
    # TODO abort this workflow if the git user triggered it is not the release manager
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check if the actor is the release manager
        run: |
          if [[ "${{ github.actor }}" != "shantalberkhof" ]]; then
            echo "Aborting workflow because the user is not the release manager."
            exit 1
          fi
      - name: Build
        run: |
          echo building and packing and app...
  DeploySimulation:
    runs-on: ubuntu-latest
    needs: BuildSimulation
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: |
          echo deploying into Test env
